name: 'Setup Java'
description: 'Composite action to set up Java with Maven caching'
inputs:
  java-version:
    description: 'Java version to set up'
    required: false
    default: '21'
  distribution:
    description: 'Java distribution to use'
    required: false
    default: 'temurin'
  cache:
    description: 'Cache Maven dependencies'
    required: false
    default: 'maven'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        cache: ${{ inputs.cache }}

    - name: Verify Java installation
      shell: bash
      run: |
        echo "Java version:"
        java -version
        echo "Maven version:"
        mvn -version

